server:
  port: 8080


logging:
  level:
    root: INFO
    com.scg.service: TRACE
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG